[pytest]
pythonpath = .
addopts = -p no:logging

markers =
    help_page: тесты для скачивания инструкций на странице помощи
    vacancy_search: тесты для проверки результатов и фильтров поиска вакансий
    public_work: тесты для проверки результатов и фильтров страницы временных оплачиваемых работ
    gpd: тесты для проверки результатов и фильтров страницы работ по гражданско-правовым договорам
    future_work: тесты для проверки результатов и фильтров страницы перспективных рабочих мест
    education: тесты для проверки результатов и фильтров страницы обучения
    foreign_citizens: тесты для проверки переходов и скачиваний на странице НПА иностранных граждан
    opfr: тесты для проверки фильтров, переходов и скачиваний на странице ОПФР-организаций
    public_resume_search: тесты для проверки поиска, фильтров и ограничений гостя на странице публичного поиска резюме
    departments: тесты для проверки фильтра, навигации и переключения вида на странице справочника отделов занятости
    activity: тесты для проверки фильтров, сортировки и навигации на странице публичного списка мероприятий
    news: тесты для проверки фильтров, сортировки и навигации на странице публичного списка новостей
    services: тесты для проверки разворота пунктов и навигации на странице публичного списка услуг