[pytest]
pythonpath = .
addopts = -p no:logging

markers =
    help_page: тесты для скачивания инструкций на странице помощи
    vacancy_search: тесты для проверки результатов и фильтров поиска вакансий
    public_work: тесты для проверки результатов и фильтров страницы временных оплачиваемых работ
    gpd: тесты для проверки результатов и фильтров страницы работ по гражданско-правовым договорам
    future_work: тесты для проверки результатов и фильтров страницы перспективных рабочих мест
    education: тесты для проверки результатов и фильтров страницы обучения