name: Playwright End-to-End Tests

on:
  push:
    branches: [ GSZ ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-22.04 # 👈 Заменили ubuntu-latest на стабильную версию 22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: python -m playwright install chromium --with-deps

    - name: Run Pytest Automation Suite
      run: |
        pytest --alluredir=allure-results